---
- name: install communications packages
  become_user: root
  pacman:
    name:
      - discord
      - signal-desktop
- name: install communications packages from AUR
  ansible.builtin.command: yay -S slack-desktop --noconfirm
