---
- name: install communications packages
  become_user: root
  pacman:
    name:
      - discord
      - signal-desktop
- name: check if slack-desktop is installed
  shell: pacman -Qi slack-desktop
  register: slack_installed
  changed_when: False
  ignore_errors: yes
- name: install slack-desktop from AUR
  ansible.builtin.command: yay -S slack-desktop --noconfirm
  when: slack_installed.rc == 1
