---
- name: install audio packages
  become_user: root
  pacman:
    name:
      - pasystray
      - jack2
      - pulseaudio-jack
      - cadence
      - qjackctl
- name: add user {{ user }} to audio group
  user:
    name: "{{ username }}"
    groups: audio
    append: yes
