---
- name: install audio packages
  become_user: root
  pacman:
    name:
      - pasystray
      - jack2
      - pulseaudio-jack
      - cadence
      - qjackctl
      - juce-docs #should probably be in a dev tooling role
      - carla
      - ladspa
      # aur/vst2sdk
- name: check if reaper-bin is installed
  shell: pacman -Qi reaper-bin
  register: reaper_installed
  changed_when: False
  ignore_errors: yes
- name: install reaper-bin from AUR
  ansible.builtin.command: yay -S reaper-bin --noconfirm
  when: reaper_installed.rc == 1
- name: add user {{ username }} to audio group
  become_user: root
  user:
    name: "{{ username }}"
    groups: audio
    append: yes
- name: Add realtime permissions for audio group
  become: true
  become_user: root
  lineinfile:
    path: /etc/security/limits.conf
    line: "@audio  -   rtprio      95"
    insertbefore: '# End of file'
- name: Add unlimited memlock for audio group
  become: true
  become_user: root
  lineinfile:
    path: /etc/security/limits.conf
    line: "@audio  -   memlock     unlimited"
    insertbefore: '# End of file'
