---
- name: install utility packages
  become_user: root
  pacman:
    name:
      - thunar
      - unzip
      - numlockx
      - flameshot
- name: check if dtrx is installed
  shell: pacman -Qi dtrx
  register: dtrx_installed
  changed_when: False
  ignore_errors: yes
- name: install dtrx from AUR
  ansible.builtin.command: yay -S dtrx --noconfirm
  when: dtrx_installed.rc == 1
