---
- name: install utility packages
  become_user: root
  pacman:
    name:
      - thunar
      - unzip
      - numlockx
- name: install utility packages from AUR
  ansible.builtin.command: yay -S dtrx --noconfirm